"""fields in user model

Revision ID: d74b6cc6e67c
Revises: 78ad28b83488
Create Date: 2022-07-14 11:42:47.844429

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d74b6cc6e67c"
down_revision = "78ad28b83488"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("about_me", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
